-- Create the table "laporan"
create table public.laporan (
  id bigint generated by default as identity primary key,
  "Date-In" date,
  "Nama" text,
  "Email" text,
  "No-Wa-Customer" text,
  "Sumber-Data" text,
  "Follow-Up" text,
  "Tanggal-FU-Terakhir" date,
  "Respond-Terakhir" text,
  "Potensi-Atau-Tidak" text,
  "Online-Meeting" text,
  "Survey-Lokasi" text,
  "Status-Closing" text,
  "Note" text,
  "Status-Pengisian" text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.laporan enable row level security;

-- Create policies (adjust as needed for your specific access control requirements)

-- Allow read access to everyone (or restrict to authenticated users)
create policy "Enable read access for all users"
on public.laporan for select
using (true);

-- Allow insert access to authenticated users
create policy "Enable insert for authenticated users only"
on public.laporan for insert
with check (auth.role() = 'authenticated');

-- Allow update access to authenticated users
create policy "Enable update for authenticated users only"
on public.laporan for update
using (auth.role() = 'authenticated');

-- Allow delete access to authenticated users
create policy "Enable delete for authenticated users only"
on public.laporan for delete
using (auth.role() = 'authenticated');
